image: node:latest

stages:
  - deploy

cache:
  paths:
  - node_modules/

before_script:
  - npm install
  - npm install -g gulp

deploy:
  stage: deploy
  script:
    - gulp build -p
    - gulp publish --host flightcontrol.pkuebler.de --user staticsites --pass $HOST_PASSWORD
